### ISSUE TITLE
Investigate <canvas> as alternative to <svg>

### ISSUE THREAD

**Issue by dwilson-icr** [JacobBrandt/timeline_heatmap#4]
Because there is the potential for this to display a lot of elements, could you investigate using a canvas instead? I'm concerned about a performance hit with SVG (unless you don't see that as an issue).

I found a cool tutorial using <custom> tags that still uses all the d3 data binding, but should see much better performance than SVG.

https://bocoup.com/weblog/d3js-and-canvas

**Comment by JacobBrandt** [comment]
It already is using a canvas.  See resolution to issue #1

**Comment by dwilson-icr** [comment]
Shows how much attention I'm paying. Nice work. I just did a quick look through the code and found a bunch of SVG references. Never mind then. Carry on!

**Comment by JacobBrandt** [comment]
No worries, it reminded me that I still have one more improvement to add to the canvas approach.  Because right now it changes the context too frequently.  I need to sort the values and then only change the fill style when I'm at a new value.  I'll write up a new issue for this.

**Comment by JacobBrandt** [comment]
#5 for reference.
